name = "pantas"
author = "pantasmc"
version = "1.21.8-1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f56c839ad2030d73e3ca2b5eceeb9f26be3230249d48759a8ea10b6865600d43"

[versions]
fabric = "0.16.14"
minecraft = "1.21.8"
