name = "pantas-plus"
author = "pantasmc"
version = "1.21.7-1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dd4f31971218c316603268881d4cff6a73a615f2ebb7c5901d513ca121cb57ff"

[versions]
fabric = "0.16.14"
minecraft = "1.21.7"
