name = "pantas"
author = "pantasmc"
version = "1.21.7-1.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1978d540e3f13eadee3a464f742e1f2d6ce16584485344f7b5d3eebd9a203150"

[versions]
fabric = "0.16.14"
minecraft = "1.21.7"
