name = "pantas"
author = "pantasmc"
version = "1.21.7-1.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6e1e0c3a4892897af5f5367ee4e225714c49c6a790f84db2b803d566b0a566b4"

[versions]
fabric = "0.16.14"
minecraft = "1.21.7"
